"" Pathogen

call pathogen#infect()

filetype plugin on
au FileType c,vim,lisp filetype indent on


"" General settings
set colorcolumn=80

syntax enable

set background=dark

colorscheme solarized

set tabstop=4
set expandtab
set shiftwidth=4
set linespace=5
set autoindent
set smartindent
set nowrap
set number
set ignorecase

set guioptions-=T  "remove toolbar
set guifont=Monaco

"" Some maps

nmap <silent> <D-7> :NERDTreeToggle<CR>
nmap <silent> <D-8> :Tlist<CR>

let mapleader = ","

"" Autocomplete

autocmd FileType javascript set omnifunc=javascriptcomplete#CompleteJS
autocmd FileType html set omnifunc=htmlcomplete#CompleteTags
autocmd FileType css set omnifunc=csscomplete#CompleteCSS
autocmd FileType xml set omnifunc=xmlcomplete#CompleteTags
autocmd FileType php set omnifunc=phpcomplete#CompletePHP

"" Syntax

au BufNewFile,BufRead *.less set filetype=less

"" Code Standard

let g:syntastic_check_on_open = 0
let g:syntastic_phpcs_conf = "--standard=CakePHPPear"

let g:syntastic_mode_map = { 'mode': 'passive',
                               \ 'active_filetypes': [],
                               \ 'passive_filetypes': ['php'] }

nmap <silent> <D-3> :SyntasticCheck<CR>:Errors<CR>

if has("gui_running")
  " GUI is running or is about to start.
  " Maximize gvim window.
  set lines=40 columns=205
endif

